---
# yaml-language-server: $schema=https://json.schemastore.org/label-commenter-config.json
area/github:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"

area/aspire:
  - changed-files:
      - any-glob-to-any-file: "Aspire/**"

area/identity:
  - changed-files:
      - any-glob-to-any-file: "Identity/**"

area/bff:
  - changed-files:
      - any-glob-to-any-file: "BFF/**"

area/tikal-backend:
  - changed-files:
      - any-glob-to-any-file: "TikalBackend/**"

area/tikal-frontend:
  - changed-files:
      - any-glob-to-any-file: "TikalFrontend/**"

area/docs:
  - changed-files:
      - any-glob-to-any-file: "docs/**"
