---
# yaml-language-server: $schema=https://json.schemastore.org/label-commenter-config.json
area/github:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"

area/identity:
  - changed-files:
      - any-glob-to-any-file: "Identity/**"

area/docs:
  - changed-files:
      - any-glob-to-any-file: "*.md"
