// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Lobbies.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Add_Lobby_InGame_Flag : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "InGame",
                schema: "Lobbies",
                table: "Lobbies",
                type: "boolean",
                nullable: false,
                defaultValue: false);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "InGame",
                schema: "Lobbies",
                table: "Lobbies");
        }
    }
}
