// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Games.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Remove_Tilemap : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Tiles_TileMaps_TileMapId",
                schema: "Games",
                table: "Tiles");

            migrationBuilder.DropTable(
                name: "TileMaps",
                schema: "Games");

            migrationBuilder.RenameColumn(
                name: "TileMapId",
                schema: "Games",
                table: "Tiles",
                newName: "GameId");

            migrationBuilder.RenameIndex(
                name: "IX_Tiles_TileMapId",
                schema: "Games",
                table: "Tiles",
                newName: "IX_Tiles_GameId");

            migrationBuilder.AddForeignKey(
                name: "FK_Tiles_Games_GameId",
                schema: "Games",
                table: "Tiles",
                column: "GameId",
                principalSchema: "Games",
                principalTable: "Games",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Tiles_Games_GameId",
                schema: "Games",
                table: "Tiles");

            migrationBuilder.RenameColumn(
                name: "GameId",
                schema: "Games",
                table: "Tiles",
                newName: "TileMapId");

            migrationBuilder.RenameIndex(
                name: "IX_Tiles_GameId",
                schema: "Games",
                table: "Tiles",
                newName: "IX_Tiles_TileMapId");

            migrationBuilder.CreateTable(
                name: "TileMaps",
                schema: "Games",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    GameId = table.Column<long>(type: "bigint", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TileMaps", x => x.Id);
                    table.ForeignKey(
                        name: "FK_TileMaps_Games_GameId",
                        column: x => x.GameId,
                        principalSchema: "Games",
                        principalTable: "Games",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_TileMaps_GameId",
                schema: "Games",
                table: "TileMaps",
                column: "GameId",
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "FK_Tiles_TileMaps_TileMapId",
                schema: "Games",
                table: "Tiles",
                column: "TileMapId",
                principalSchema: "Games",
                principalTable: "TileMaps",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
