// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Games.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Initial_Game_Structure : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "Games");

            migrationBuilder.CreateTable(
                name: "Games",
                schema: "Games",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    LobbyId = table.Column<long>(type: "bigint", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Games", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Players",
                schema: "Games",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    UserId = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    Colour = table.Column<int>(type: "integer", nullable: false),
                    Points = table.Column<int>(type: "integer", nullable: false),
                    GameId = table.Column<long>(type: "bigint", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Players", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Players_Games_GameId",
                        column: x => x.GameId,
                        principalSchema: "Games",
                        principalTable: "Games",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "TileMaps",
                schema: "Games",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    GameId = table.Column<long>(type: "bigint", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TileMaps", x => x.Id);
                    table.ForeignKey(
                        name: "FK_TileMaps_Games_GameId",
                        column: x => x.GameId,
                        principalSchema: "Games",
                        principalTable: "Games",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Tiles",
                schema: "Games",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    TileMapId = table.Column<long>(type: "bigint", nullable: false),
                    TileType = table.Column<int>(type: "integer", nullable: false),
                    QCoordinate = table.Column<int>(type: "integer", nullable: false),
                    RCoordinate = table.Column<int>(type: "integer", nullable: false),
                    NorthCost = table.Column<int>(type: "integer", nullable: false),
                    NorthEastCost = table.Column<int>(type: "integer", nullable: false),
                    NorthWestCost = table.Column<int>(type: "integer", nullable: false),
                    SouthCost = table.Column<int>(type: "integer", nullable: false),
                    SouthEastCost = table.Column<int>(type: "integer", nullable: false),
                    SouthWestCost = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Tiles", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Tiles_TileMaps_TileMapId",
                        column: x => x.TileMapId,
                        principalSchema: "Games",
                        principalTable: "TileMaps",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "TroopAssignments",
                schema: "Games",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    TileId = table.Column<long>(type: "bigint", nullable: false),
                    TroopType = table.Column<int>(type: "integer", nullable: false),
                    Count = table.Column<int>(type: "integer", nullable: false),
                    PlayerId = table.Column<long>(type: "bigint", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TroopAssignments", x => x.Id);
                    table.ForeignKey(
                        name: "FK_TroopAssignments_Players_PlayerId",
                        column: x => x.PlayerId,
                        principalSchema: "Games",
                        principalTable: "Players",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_TroopAssignments_Tiles_TileId",
                        column: x => x.TileId,
                        principalSchema: "Games",
                        principalTable: "Tiles",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Games_LobbyId",
                schema: "Games",
                table: "Games",
                column: "LobbyId",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Players_GameId",
                schema: "Games",
                table: "Players",
                column: "GameId");

            migrationBuilder.CreateIndex(
                name: "IX_Players_UserId",
                schema: "Games",
                table: "Players",
                column: "UserId",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_TileMaps_GameId",
                schema: "Games",
                table: "TileMaps",
                column: "GameId",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Tiles_TileMapId",
                schema: "Games",
                table: "Tiles",
                column: "TileMapId");

            migrationBuilder.CreateIndex(
                name: "IX_TroopAssignments_PlayerId",
                schema: "Games",
                table: "TroopAssignments",
                column: "PlayerId");

            migrationBuilder.CreateIndex(
                name: "IX_TroopAssignments_TileId",
                schema: "Games",
                table: "TroopAssignments",
                column: "TileId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "TroopAssignments",
                schema: "Games");

            migrationBuilder.DropTable(
                name: "Players",
                schema: "Games");

            migrationBuilder.DropTable(
                name: "Tiles",
                schema: "Games");

            migrationBuilder.DropTable(
                name: "TileMaps",
                schema: "Games");

            migrationBuilder.DropTable(
                name: "Games",
                schema: "Games");
        }
    }
}
