// <auto-generated />
using System.Collections.Generic;
using Games.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Games.Infrastructure.Database.Migrations
{
    [DbContext(typeof(GamesDbContext))]
    [Migration("20260817171848_TempleLevel")]
    partial class TempleLevel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Games")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Games.Domain.Entities.Game", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("LobbyId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LobbyId")
                        .IsUnique();

                    b.ToTable("Games", "Games");
                });

            modelBuilder.Entity("Games.Domain.Entities.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Colour")
                        .HasColumnType("integer");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Players", "Games");
                });

            modelBuilder.Entity("Games.Domain.Entities.Tile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("TileMapId")
                        .HasColumnType("bigint");

                    b.Property<int>("TileType")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Coordinate", "Games.Domain.Entities.Tile.Coordinate#HexCoordinate", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Q")
                                .HasColumnType("integer")
                                .HasColumnName("QCoordinate");

                            b1.Property<int>("R")
                                .HasColumnType("integer")
                                .HasColumnName("RCoordinate");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Costs", "Games.Domain.Entities.Tile.Costs#TravelCosts", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("North")
                                .HasColumnType("integer")
                                .HasColumnName("NorthCost");

                            b1.Property<int>("NorthEast")
                                .HasColumnType("integer")
                                .HasColumnName("NorthEastCost");

                            b1.Property<int>("Northwest")
                                .HasColumnType("integer")
                                .HasColumnName("NorthWestCost");

                            b1.Property<int>("South")
                                .HasColumnType("integer")
                                .HasColumnName("SouthCost");

                            b1.Property<int>("SouthEast")
                                .HasColumnType("integer")
                                .HasColumnName("SouthEastCost");

                            b1.Property<int>("SouthWest")
                                .HasColumnType("integer")
                                .HasColumnName("SouthWestCost");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TileMapId");

                    b.ToTable("Tiles", "Games");

                    b.HasDiscriminator<int>("TileType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Games.Domain.Entities.TileMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("TileMaps", "Games");
                });

            modelBuilder.Entity("Games.Domain.Entities.TroopAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<long>("TileId")
                        .HasColumnType("bigint");

                    b.Property<int>("TroopType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TileId");

                    b.ToTable("TroopAssignments", "Games");
                });

            modelBuilder.Entity("Games.Domain.Entities.EmptyTile", b =>
                {
                    b.HasBaseType("Games.Domain.Entities.Tile");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Games.Domain.Entities.TempleTile", b =>
                {
                    b.HasBaseType("Games.Domain.Entities.Tile");

                    b.Property<int>("TempleLevel")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Games.Domain.Entities.TreasureTile", b =>
                {
                    b.HasBaseType("Games.Domain.Entities.Tile");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Games.Domain.Entities.VolcanoTile", b =>
                {
                    b.HasBaseType("Games.Domain.Entities.Tile");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Games.Domain.Entities.Player", b =>
                {
                    b.HasOne("Games.Domain.Entities.Game", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Games.Domain.Entities.Tile", b =>
                {
                    b.HasOne("Games.Domain.Entities.TileMap", "TileMap")
                        .WithMany("Tiles")
                        .HasForeignKey("TileMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TileMap");
                });

            modelBuilder.Entity("Games.Domain.Entities.TileMap", b =>
                {
                    b.HasOne("Games.Domain.Entities.Game", "Game")
                        .WithOne("TileMap")
                        .HasForeignKey("Games.Domain.Entities.TileMap", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Games.Domain.Entities.TroopAssignment", b =>
                {
                    b.HasOne("Games.Domain.Entities.Player", "Player")
                        .WithMany("TroopAssignments")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Games.Domain.Entities.Tile", "Tile")
                        .WithMany("TroopAssignments")
                        .HasForeignKey("TileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Tile");
                });

            modelBuilder.Entity("Games.Domain.Entities.Game", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("TileMap")
                        .IsRequired();
                });

            modelBuilder.Entity("Games.Domain.Entities.Player", b =>
                {
                    b.Navigation("TroopAssignments");
                });

            modelBuilder.Entity("Games.Domain.Entities.Tile", b =>
                {
                    b.Navigation("TroopAssignments");
                });

            modelBuilder.Entity("Games.Domain.Entities.TileMap", b =>
                {
                    b.Navigation("Tiles");
                });
#pragma warning restore 612, 618
        }
    }
}
