// <auto-generated />
using System.Collections.Generic;
using Games.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Games.Infrastructure.Database.Migrations
{
    [DbContext(typeof(GamesDbContext))]
    [Migration("20260814181728_Initial_Games_And_Players")]
    partial class Initial_Games_And_Players
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Games")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Games.Domain.Entities.Game", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("LobbyId")
                        .HasColumnType("bigint");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TileMap", "Games.Domain.Entities.Game.TileMap#TileMap", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Tiles", "Games.Domain.Entities.Game.TileMap#TileMap.Tiles#List<KeyValuePair<HexCoordinate, Tile>>", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<int>("Capacity");

                                    b2
                                        .ToJson("Tiles")
                                        .HasColumnType("jsonb");
                                });

                            b1
                                .ToJson("TileMap")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id");

                    b.HasIndex("LobbyId")
                        .IsUnique();

                    b.ToTable("Games", "Games");
                });

            modelBuilder.Entity("Games.Domain.Entities.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Colour")
                        .HasColumnType("integer");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Players", "Games");
                });

            modelBuilder.Entity("Games.Domain.Entities.Player", b =>
                {
                    b.HasOne("Games.Domain.Entities.Game", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Games.Domain.Entities.Game", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
