---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Snyk Scan

on:
  workflow_call:
    inputs:
      project-directory:
        required: true
        type: string
    secrets:
      SNYK_TOKEN:
        required: true

jobs:
  snyk-scan:
    name: Snyk Scan
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ${{ inputs.project-directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: true

      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Setup dotnet
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          global-json-file: global.json
          cache: true
          cache-dependency-path: "./**/packages.lock.json"

      - name: Restore projects
        run: |
          dotnet restore --locked-mode
          dotnet restore Modules --locked-mode

      - name: Snyk code test
        run: |
          snyk code test \
          --sarif-file-output=snyk-code.sarif \
          --report \
          --target-name="${{ inputs.project-directory }}-Code" \
          --project-name="${{ inputs.project-directory }}Code-Analysis" \
          || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Snyk open source test
        run: snyk test --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Snyk open source monitor
        run: |
          snyk monitor \
          --all-projects \
          --remote-repo-url="${{ inputs.project-directory }}-Dependencies"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
