---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Snyk Scan

on:
  workflow_call:
    inputs:
      project-directory:
        required: true
        type: string
    secrets:
      SNYK_TOKEN:
        required: true

jobs:
  snyk-scan:
    name: Snyk Scan
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ${{ inputs.project-directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: true

      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Code test
        run: snyk code test --sarif > snyk-code.sarif || true

      - name: Snyk Open Source monitor
        run: snyk monitor --all-projects

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ inputs.project-directory }}/snyk-code.sarif
