---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Unit Tests

on:
  workflow_call:
    inputs:
      project-directory:
        required: true
        type: string

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          lfs: true

      - name: Setup dotnet
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          global-json-file: global.json
          cache: true
          cache-dependency-path: "${{ inputs.project-directory }}/**/*.Tests/packages.lock.json"

      - name: Restore projects
        run: dotnet restore ${{ inputs.project-directory }}/Modules --locked-mode

      - name: Build projects
        run: dotnet build ${{ inputs.project-directory }}/Modules --no-restore

      - name: Run Unit Tests
        run: |
          dotnet test \
            --solution ${{ inputs.project-directory }}/Modules/Tests.slnf \
            --coverlet \
            --coverlet-output-format opencover \
            --results-directory TestResults/UnitTests \
            --no-build

      - name: Upload test results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ inputs.project-directory }}-unit-test-coverage
          path: TestResults
        if: ${{ always() }}
