---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Integration Tests

on:
  workflow_call:
    inputs:
      project-directory:
        required: true
        type: string

jobs:
  unit-test:
    name: Integration Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: true

      - name: Setup dotnet
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          global-json-file: global.json
          cache: true
          cache-dependency-path: "${{ inputs.project-directory }}/${{ inputs.project-directory }}.IntegrationTests/packages.lock.json"

      - name: Restore projects
        run: dotnet restore ${{ inputs.project-directory }}/${{ inputs.project-directory }}.IntegrationTests --locked-mode

      - name: Build projects
        run: dotnet build ${{ inputs.project-directory }}/${{ inputs.project-directory }}.IntegrationTests --no-restore

      - name: Run Integration Tests
        run: |
          dotnet test \
            --project ${{ inputs.project-directory }}/${{ inputs.project-directory }}.IntegrationTests \
            --coverlet \
            --coverlet-output-format opencover \
            --results-directory TestResults/IntegrationTests \
            --no-build

      - name: Upload test results
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: ${{ inputs.project-directory }}-integration-test-coverage
          path: TestResults
        if: ${{ always() }}
