---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Sonarqube scan

on:
  workflow_call:
    inputs:
      project-directory:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  sonarqube-scan:
    name: Sonarqube scan
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          lfs: true

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.sources="{{ inputs.project-directory }}"
            -Dsonar.projectKey="{{ inputs.project-directory }}"
            -Dsonar.organization="fmahdi09"
 