---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: BFF CI/CD

on:
  push:
    branches:
      - main
    paths:
      - BFF/**
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - BFF/**

jobs:
  format:
    name: Format
    uses: ./.github/workflows/dotnet-format.yaml
    with:
      project-directory: BFF

  release:
    name: Release
    needs: format
    permissions:
      contents: write
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/create-release.yaml
    with:
      project-directory: BFF
      project-name: bff

  migrate:
    name: Migrate
    needs: release
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/dotnet-bff-migrate-db.yaml
    secrets: inherit
    with:
      project-directory: BFF
      keyvault-name: tikal-tikalbff-keyvault

  deploy:
    name: Deploy
    needs: [ migrate, release ]
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-release.yaml
    secrets: inherit
    with:
      dockerfile: ./BFF/Dockerfile
      project-name: bff
      version: ${{ needs.release.outputs.version }}
