---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - TikalBackend/**
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - TikalBackend/**

jobs:
  format:
    name: Format
    uses: ./.github/workflows/dotnet-format.yaml
    with:
      project-directory: TikalBackend

  unit-tests:
    name: Unit Tests
    needs: format
    uses: ./.github/workflows/dotnet-unit-test.yaml
    with:
      project-directory: TikalBackend

  integration-tests:
    name: Integration Tests
    needs: format
    uses: ./.github/workflows/dotnet-integration-test.yaml
    with:
      project-directory: TikalBackend

  sonar-scan:
    name: SonarQube Scan
    needs: [ unit-tests, integration-tests ]
    uses: ./.github/workflows/dotnet-sonar-scan.yaml
    with:
      project-directory: TikalBackend
    secrets:
      SONAR_TOKEN: ${{ secrets.TIKAL_BACKEND_SONAR_TOKEN }}

  release:
    name: Release
    needs: sonar-scan
    permissions:
      contents: write
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/shared-create-release.yaml
    with:
      project-directory: TikalBackend
      project-name: tikal-backend

  migrate:
    name: Migrate
    needs: release
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/migrate-db.yaml
    secrets: inherit
    with:
      project-directory: TikalBackend
      keyvault-name: tikal-tikalapi-keyvault

  deploy:
    name: Deploy
    needs: [ migrate, release ]
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/shared-deploy-release.yaml
    secrets: inherit
    with:
      dockerfile: ./TikalBackend/TikalBackend.WebHost/Dockerfile
      project-name: tikal-backend
      version: ${{ needs.release.outputs.version }}
